apply plugin: 'com.android.application'

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.github.lukaspili.reactivebilling.sample"
        minSdkVersion 16
        targetSdkVersion 33
        versionCode 3
        versionName "1.1"
    }

    signingConfigs {
        release {
            storeFile file("../keystore.jks")
            storePassword "reactivebilling"
            keyAlias "reactivebilling"
            keyPassword "reactivebilling"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
}

dependencies {
    implementation project(':library')

    implementation 'com.android.support:appcompat-v7:23.3.0'
    implementation 'com.android.support:recyclerview-v7:23.3.0'
    implementation 'com.android.support:design:23.3.0'

    implementation 'io.reactivex:rxjava:1.1.5'
    implementation 'io.reactivex:rxandroid:1.2.0'
}
